//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace QBDrumMap.Properties
{
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QBDrumMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   QBDrumMap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppDisplayName
        {
            get
            {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Do you want to set articulation automatically? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArticulationAutomaticFill
        {
            get
            {
                return ResourceManager.GetString("ArticulationAutomaticFill", resourceCulture);
            }
        }

        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonAdd
        {
            get
            {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonImport
        {
            get
            {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }

        /// <summary>
        ///   Move Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonMoveBottom
        {
            get
            {
                return ResourceManager.GetString("ButtonMoveBottom", resourceCulture);
            }
        }

        /// <summary>
        ///   Move Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonMoveDown
        {
            get
            {
                return ResourceManager.GetString("ButtonMoveDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Move Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonMoveTop
        {
            get
            {
                return ResourceManager.GetString("ButtonMoveTop", resourceCulture);
            }
        }

        /// <summary>
        ///   Move Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonMoveUp
        {
            get
            {
                return ResourceManager.GetString("ButtonMoveUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Open File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonOpenFile
        {
            get
            {
                return ResourceManager.GetString("ButtonOpenFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSearch
        {
            get
            {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Compress Forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompressForward
        {
            get
            {
                return ResourceManager.GetString("CompressForward", resourceCulture);
            }
        }

        /// <summary>
        ///   Stuff blank lines back? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompressForwardConfirm
        {
            get
            {
                return ResourceManager.GetString("CompressForwardConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Do you want automatic interpolation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfiramAutomaticInterpolation
        {
            get
            {
                return ResourceManager.GetString("ConfiramAutomaticInterpolation", resourceCulture);
            }
        }

        /// <summary>
        ///   Set the same value to the same name? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmAutoFill
        {
            get
            {
                return ResourceManager.GetString("ConfirmAutoFill", resourceCulture);
            }
        }

        /// <summary>
        ///   Select Articulation Source Kit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextKitPitchesArticulationSourceIsEmpty
        {
            get
            {
                return ResourceManager.GetString("ContextKitPitchesArticulationSourceIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Compress Forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextKitPitchesCompressForward
        {
            get
            {
                return ResourceManager.GetString("ContextKitPitchesCompressForward", resourceCulture);
            }
        }

        /// <summary>
        ///   Copy Articulation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextKitPitchesCopyArticulation
        {
            get
            {
                return ResourceManager.GetString("ContextKitPitchesCopyArticulation", resourceCulture);
            }
        }

        /// <summary>
        ///   Copy Text To Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextKitPitchesCopyTextToClibBoard
        {
            get
            {
                return ResourceManager.GetString("ContextKitPitchesCopyTextToClibBoard", resourceCulture);
            }
        }

        /// <summary>
        ///   Import Drum Map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextKitPitchesImportDrmMap
        {
            get
            {
                return ResourceManager.GetString("ContextKitPitchesImportDrmMap", resourceCulture);
            }
        }

        /// <summary>
        ///   Paste Text From Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextKitPitchesPasteTextFromClibBoard
        {
            get
            {
                return ResourceManager.GetString("ContextKitPitchesPasteTextFromClibBoard", resourceCulture);
            }
        }

        /// <summary>
        ///   Reset Orde By Pitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextKitPitchesResetOrdeByPitch
        {
            get
            {
                return ResourceManager.GetString("ContextKitPitchesResetOrdeByPitch", resourceCulture);
            }
        }

        /// <summary>
        ///   Show Articulation Map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextKitPitchesShowArticulationMap
        {
            get
            {
                return ResourceManager.GetString("ContextKitPitchesShowArticulationMap", resourceCulture);
            }
        }

        /// <summary>
        ///   Copy To Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyTextClipToClipBoardComplete
        {
            get
            {
                return ResourceManager.GetString("CopyTextClipToClipBoardComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Auto Fill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogAutomaticFill
        {
            get
            {
                return ResourceManager.GetString("DialogAutomaticFill", resourceCulture);
            }
        }

        /// <summary>
        ///   &apos;{0}&apos; is already in use! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DuplicateNaem
        {
            get
            {
                return ResourceManager.GetString("DuplicateNaem", resourceCulture);
            }
        }

        /// <summary>
        ///   About QBDrumMap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help_About
        {
            get
            {
                return ResourceManager.GetString("Help_About", resourceCulture);
            }
        }

        /// <summary>
        ///   Import DrumMap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportDrumMap
        {
            get
            {
                return ResourceManager.GetString("ImportDrumMap", resourceCulture);
            }
        }

        /// <summary>
        ///   Incorrect MIDI Data! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncorrectMIDIData
        {
            get
            {
                return ResourceManager.GetString("IncorrectMIDIData", resourceCulture);
            }
        }

        /// <summary>
        ///   {0} Name must be {1} characters or less に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LenghtLessLThan
        {
            get
            {
                return ResourceManager.GetString("LenghtLessLThan", resourceCulture);
            }
        }

        /// <summary>
        ///   {0} Name must be at least {1} and no more than {2} characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LengthBetween
        {
            get
            {
                return ResourceManager.GetString("LengthBetween", resourceCulture);
            }
        }

        /// <summary>
        ///   An error occurred during MIDI data processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MIDIError
        {
            get
            {
                return ResourceManager.GetString("MIDIError", resourceCulture);
            }
        }

        /// <summary>
        ///   Paste Complete! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteComplete
        {
            get
            {
                return ResourceManager.GetString("PasteComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Are you sure you want to run the paste? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteConfirm
        {
            get
            {
                return ResourceManager.GetString("PasteConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Reset Order By PItch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetOrderByPitch
        {
            get
            {
                return ResourceManager.GetString("ResetOrderByPitch", resourceCulture);
            }
        }

        /// <summary>
        ///   May I sort by pitch? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetOrderByPitchConfirm
        {
            get
            {
                return ResourceManager.GetString("ResetOrderByPitchConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Select Cubase Install Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectCubaseInstallPath
        {
            get
            {
                return ResourceManager.GetString("SelectCubaseInstallPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Convert MIDI Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ConvertMIDIFormat
        {
            get
            {
                return ResourceManager.GetString("Setting_ConvertMIDIFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Cubase Install Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_CubaseInstallPath
        {
            get
            {
                return ResourceManager.GetString("Setting_CubaseInstallPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Export Cubase Base On Default Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ExportCubaseBaseOnDefaultPath
        {
            get
            {
                return ResourceManager.GetString("Setting_ExportCubaseBaseOnDefaultPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Export Cubase Default Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ExportCubaseDefaultPath
        {
            get
            {
                return ResourceManager.GetString("Setting_ExportCubaseDefaultPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Export Note Mapper Default Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ExportNoteMapperDefaultPath
        {
            get
            {
                return ResourceManager.GetString("Setting_ExportNoteMapperDefaultPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Export QB Drummer Default Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ExportQBDrummerDefaultPath
        {
            get
            {
                return ResourceManager.GetString("Setting_ExportQBDrummerDefaultPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Export Studio One Default Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ExportStudioOneDefaultPath
        {
            get
            {
                return ResourceManager.GetString("Setting_ExportStudioOneDefaultPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Export Text Default Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ExportTextDefaultPath
        {
            get
            {
                return ResourceManager.GetString("Setting_ExportTextDefaultPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Is Open The Last File Opened に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_IsOpenTheLastFileOpened
        {
            get
            {
                return ResourceManager.GetString("Setting_IsOpenTheLastFileOpened", resourceCulture);
            }
        }

        /// <summary>
        ///   Last Import File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_LastImportFilePath
        {
            get
            {
                return ResourceManager.GetString("Setting_LastImportFilePath", resourceCulture);
            }
        }

        /// <summary>
        ///   Last Opened File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_LastOpenedFilePath
        {
            get
            {
                return ResourceManager.GetString("Setting_LastOpenedFilePath", resourceCulture);
            }
        }

        /// <summary>
        ///   MIDI In Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_MidiInDevice
        {
            get
            {
                return ResourceManager.GetString("Setting_MidiInDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   MIDI In Fixed Pitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_MidiInFixedPitch
        {
            get
            {
                return ResourceManager.GetString("Setting_MidiInFixedPitch", resourceCulture);
            }
        }

        /// <summary>
        ///   MIDI Out Channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_MidiOutChannel
        {
            get
            {
                return ResourceManager.GetString("Setting_MidiOutChannel", resourceCulture);
            }
        }

        /// <summary>
        ///   MIDI Out Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_MidiOutDevice
        {
            get
            {
                return ResourceManager.GetString("Setting_MidiOutDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Use Articulation Pitch Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_UseArticulationPitchName
        {
            get
            {
                return ResourceManager.GetString("Setting_UseArticulationPitchName", resourceCulture);
            }
        }

        /// <summary>
        ///   Use Articulation When Exporting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_UseArticulationWhenExporting
        {
            get
            {
                return ResourceManager.GetString("Setting_UseArticulationWhenExporting", resourceCulture);
            }
        }

        /// <summary>
        ///   Sound Check Velocity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SoundCheckVelocity
        {
            get
            {
                return ResourceManager.GetString("SoundCheckVelocity", resourceCulture);
            }
        }

        /// <summary>
        ///   Articulations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ArticulationsPage
        {
            get
            {
                return ResourceManager.GetString("Title_ArticulationsPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Convert MIDI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ConvertMidiPage
        {
            get
            {
                return ResourceManager.GetString("Title_ConvertMidiPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ExportPage
        {
            get
            {
                return ResourceManager.GetString("Title_ExportPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Parts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_PartsPage
        {
            get
            {
                return ResourceManager.GetString("Title_PartsPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Plugin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_PluginPage
        {
            get
            {
                return ResourceManager.GetString("Title_PluginPage", resourceCulture);
            }
        }
    }
}
